/*
 * File: app/view/vwprtPrincipalViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.vwprtPrincipalViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.vwprtprincipal',

    onCbParametroPrincipalSelect: function(combo, record, eOpts) {
        if(BANDERA === 0){
            Ext.getCmp('PanelCentral').removeAll();
            Ext.Ajax.request(
            {
                url: '../servidor/tramites/usuario/getRolUsuario',
                method: 'post',
                params:{
                    parametro: Ext.getCmp('cbParametroPrincipal').getValue(),
                    usuario: USUARIO
                },
                success: function(response, opts)
                {
                    var responseData = Ext.JSON.decode(response.responseText);
                    var roles = responseData.data;

                    if(VERIFICADO && roles!== 'undefined'){
                        Ext.getCmp('btnConsultarTramite').setVisible(false);
                        Ext.getCmp('btnDireccionarTramite').setVisible(false);
                        Ext.getCmp('btnAdministrarTramite').setVisible(false);
                        Ext.getCmp('btnAdminGeneral').setVisible(false);
                        Ext.getCmp('btnConsultaGeneral').setVisible(false);

                        if(Ext.Array.contains(roles, 1)===true){
                            Ext.getCmp('btnConsultarTramite').setVisible(true);
                        }
                        if(Ext.Array.contains(roles, 2)===true){
                            Ext.getCmp('btnDireccionarTramite').setVisible(true);
                        }
                        if(Ext.Array.contains(roles, 3)===true){
                            Ext.getCmp('btnAdministrarTramite').setVisible(true);
                        }
                        if(Ext.Array.contains(roles, 4)===true){
                            Ext.getCmp('btnAdminGeneral').setVisible(true);
                        }
                        if(Ext.Array.contains(roles, 5)===true){
                            Ext.getCmp('btnConsultaGeneral').setVisible(true);
                        }
                    }
                },

                failure: function(response, opts)
                {
                    Ext.Msg.show({
                        title:'Error',
                        msg: 'Hubo un error',
                        buttons: Ext.Msg.OK,
                        icon: Ext.MessageBox.WARNING
                    });
                }
            });
        }
        else{
            Ext.Msg.alert('Alerta','Se encuentra en medio del direccionamiento');
        }
    },

    onCbParametroPrincipalExpand: function(field, eOpts) {
        var strParametroPri = Ext.getCmp('cbParametroPrincipal').getStore();
        strParametroPri.proxy.extraParams={
            usuario:USUARIO
        };
        strParametroPri.load();
    },

    onBtnNuevoTramiteClick: function(button, e, eOpts) {
        var parametroNum = Ext.getCmp('cbParametroPrincipal').getValue();
        if(parametroNum!== null){
            if(!Ext.getCmp('pnlNuevo'))
            {
                if (BANDERA ===0){
                    Ext.getCmp('PanelCentral').removeAll();
                    var win = Ext.create('Tramites.view.panel.pnlNuevo');
                    this.getView().down('#PanelCentral').add(win);
                    win.show();

                }
                else{
                    Ext.Msg.alert('Alerta','Se encuentra en medio del direccionamiento');
                }

            }
        }
        else{
            Ext.Msg.alert('Alerta','Seleccione un parámetro');
        }
    },

    onBtnConsultaGeneralClick: function(button, e, eOpts) {
        if(!Ext.getCmp('pnlConsultaGeneral'))
        {
            if (BANDERA ===0){//cuando bandera esta en uno no permite moverse a otras ventanas ya que se encuentra en direcionamiento
                Ext.getCmp('PanelCentral').removeAll();
                var win = Ext.create('Tramites.view.panel.pnlConsultaGeneral');
                this.getView().down('#PanelCentral').add(win);
                win.show();

            }
            else{
                Ext.Msg.alert('Alerta','Se encuentra en medio del direccionamiento');
            }

        }
    },

    onBtnConsultarTramiteClick: function(button, e, eOpts) {
        if(!Ext.getCmp('pnlConsultar'))
        {
            if (BANDERA ===0){//cuando bandera esta en uno no permite moverse a otras ventanas ya que se encuentra en direcionamiento
                Ext.getCmp('PanelCentral').removeAll();
                var win = Ext.create('Tramites.view.panel.pnlConsultar');
                this.getView().down('#PanelCentral').add(win);
                win.show();

            }
            else{
                Ext.Msg.alert('Alerta','Se encuentra en medio del direccionamiento');
            }

        }
    },

    onBtnDireccionarTramiteClick: function(button, e, eOpts) {
        var parametroNum = Ext.getCmp('cbParametroPrincipal').getValue();
        if(parametroNum!== null){
            if(!Ext.getCmp('pnlDireccionar'))
            {
                if (BANDERA ===0){//cuando bandera esta en uno no permite moverse a otras ventanas ya que se encuentra en direcionamiento

                    Ext.getCmp('PanelCentral').removeAll();
                    var win = Ext.create('Tramites.view.panel.pnlDireccionar');
                    this.getView().down('#PanelCentral').add(win);
                    win.show();
                    Ext.getCmp('ArbolUnidad').getStore().load();

                }
                else{
                    Ext.Msg.alert('Alerta','Se encuentra en medio del direccionamiento');
                }

            }
        }
        else{
            Ext.Msg.alert('Alerta','Seleccione un parámetro');
        }
    },

    onBtnAdministrarTramiteClick: function(button, e, eOpts) {
        if(!Ext.getCmp('pnlAdministrar'))
        {
            if (BANDERA ===0){//cuando bandera esta en uno no permite moverse a otras ventanas ya que se encuentra en direcionamiento
                Ext.getCmp('PanelCentral').removeAll();
                var win = Ext.create('Tramites.view.panel.pnlAdministrar');
                this.getView().down('#PanelCentral').add(win);
                win.show();

            }
            else{
                Ext.Msg.alert('Alerta','Se encuentra en medio del direccionamiento');
            }



        }
    },

    onBtnAdminGeneralClick: function(button, e, eOpts) {
        if(!Ext.getCmp('pnlAdminGeneral'))
        {
            if (BANDERA === 0){//cuando bandera esta en uno no permite moverse a otras ventanas ya que se encuentra en direcionamiento
                Ext.getCmp('PanelCentral').removeAll();
                var win = Ext.create('Tramites.view.panel.pnlAdminGeneral');
                this.getView().down('#PanelCentral').add(win);
                win.show();
            }
            else{
                Ext.Msg.alert('Alerta','Se encuentra en medio del direccionamiento');
            }
        }
    },

    onButtonSalirPClick: function(button, e, eOpts) {
        if (BANDERA ===0){//cuando bandera esta en uno no permite moverse a otras ventanas ya que se encuentra en direcionamiento
            var viewMain = this;
            Ext.Ajax.request
            (
            {
                url: '../servidor/login/logout',
                success:function(response,options)
                {
                    var responseData = Ext.JSON.decode(response.responseText);
                    if(responseData.success)
                    {
                        viewMain.getView().destroy();
                        Ext.create('Tramites.view.vwprtLogin', {renderTo: Ext.getBody()});
                    }
                }
            }
            );
        }
        else{
            Ext.Msg.alert('Alerta','Se encuentra en medio del direccionamiento');
        }
    }

});
