/*
 * File: app/view/administracion/AsuntosParametrosViewModel3.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.administracion.AsuntosParametrosViewModel3', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.administracion.usuarioparametrobasico',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Memory'
    ],

    stores: {
        asuntoModels: {
            model: 'Tramites.model.AsuntoModel',
            data: [
                {
                    ASU_CODIGO: 902,
                    ASU_DESCRIPCION: 'quam',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 791,
                    ASU_DESCRIPCION: 'reiciendis',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 915,
                    ASU_DESCRIPCION: 'facere',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 175,
                    ASU_DESCRIPCION: 'et',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 935,
                    ASU_DESCRIPCION: 'deleniti',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 863,
                    ASU_DESCRIPCION: 'pariatur',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 120,
                    ASU_DESCRIPCION: 'voluptates',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 388,
                    ASU_DESCRIPCION: 'qui',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 574,
                    ASU_DESCRIPCION: 'quasi',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 215,
                    ASU_DESCRIPCION: 'nihil',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 733,
                    ASU_DESCRIPCION: 'incidunt',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 647,
                    ASU_DESCRIPCION: 'unde',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 834,
                    ASU_DESCRIPCION: 'et',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 680,
                    ASU_DESCRIPCION: 'ad',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 558,
                    ASU_DESCRIPCION: 'ex',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 710,
                    ASU_DESCRIPCION: 'dolorem',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 228,
                    ASU_DESCRIPCION: 'tempore',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 467,
                    ASU_DESCRIPCION: 'facilis',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 807,
                    ASU_DESCRIPCION: 'consequatur',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 485,
                    ASU_DESCRIPCION: 'odio',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 361,
                    ASU_DESCRIPCION: 'assumenda',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 371,
                    ASU_DESCRIPCION: 'natus',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 695,
                    ASU_DESCRIPCION: 'unde',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 454,
                    ASU_DESCRIPCION: 'est',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 825,
                    ASU_DESCRIPCION: 'fugit',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 12,
                    ASU_DESCRIPCION: 'iste',
                    ASU_ACTIVO: false
                },
                {
                    ASU_CODIGO: 299,
                    ASU_DESCRIPCION: 'asperiores',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 292,
                    ASU_DESCRIPCION: 'eius',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 716,
                    ASU_DESCRIPCION: 'numquam',
                    ASU_ACTIVO: true
                },
                {
                    ASU_CODIGO: 136,
                    ASU_DESCRIPCION: 'enim',
                    ASU_ACTIVO: false
                }
            ],
            proxy: {
                type: 'memory'
            }
        }
    }

});