/*
 * File: app/model/RegistroModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.model.RegistroModel', {
    extend: 'Ext.data.Model',
    alias: 'model.registromodel',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Date',
        'Ext.data.field.Boolean'
    ],

    idProperty: 'TRA_CODIGO',

    fields: [
        {
            type: 'int',
            name: 'TRA_CODIGO'
        },
        {
            type: 'int',
            name: 'ASU_CODIGO'
        },
        {
            type: 'string',
            name: 'USR_USUARIO'
        },
        {
            type: 'string',
            name: 'TRA_OFICIO'
        },
        {
            type: 'string',
            name: 'TRA_BENEFICIARIO1'
        },
        {
            type: 'string',
            name: 'TRA_BENEFICIARIO2'
        },
        {
            type: 'string',
            name: 'TRA_CEDULA1'
        },
        {
            type: 'string',
            name: 'TRA_CEDULA2'
        },
        {
            type: 'string',
            name: 'TRA_PROYECTO'
        },
        {
            type: 'string',
            name: 'TRA_COMPROMISO'
        },
        {
            type: 'string',
            name: 'TRA_PERSONA_AUTORIZA'
        },
        {
            type: 'string',
            name: 'TRA_TELEFONO'
        },
        {
            type: 'float',
            name: 'TRA_VALOR'
        },
        {
            type: 'int',
            name: 'TRA_DETALLE_FACTURA'
        },
        {
            type: 'date',
            name: 'TRA_FECHA_VIAJE_VIATICO',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'string',
            name: 'TRA_DESTINO_VIATICO'
        },
        {
            type: 'string',
            name: 'TRA_RESPONSABLE_VIATICO'
        },
        {
            type: 'string',
            name: 'TRA_PERSONAS_ADIC_VIATICO'
        },
        {
            type: 'string',
            name: 'TRA_OBSERV_VIAJE_VIATICO'
        },
        {
            name: 'TRA_FECHARECIBIDO'
        },
        {
            type: 'boolean',
            name: 'TRA_RECIBIDO'
        },
        {
            type: 'string',
            name: 'TRA_GASTO'
        },
        {
            type: 'int',
            name: 'TRA_PRM_ID'
        },
        {
            type: 'string',
            name: 'TRA_DESCRIPCION'
        },
        {
            type: 'int',
            name: 'UND_CODIGO'
        },
        {
            name: 'TRA_FECHA'
        },
        {
            type: 'boolean',
            name: 'TRA_ANULADO'
        },
        {
            type: 'string',
            name: 'UND_NOMBRE'
        },
        {
            type: 'string',
            name: 'ASU_DESCRIPCION'
        },
        {
            type: 'string',
            name: 'PRM_NOMBRE'
        },
        {
            type: 'date',
            name: 'TRA_FECHA_VIAJE_FIN_VIATICO',
            dateFormat: 'Y-m-d'
        },
        {
            type: 'string',
            name: 'TRA_POSICION'
        },
        {
            type: 'string',
            name: 'TRA_MONEDA'
        }
    ]
});