/*
 * File: app/store/Registro.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.store.Registro', {
    extend: 'Ext.data.Store',
    alias: 'store.registrostore',

    requires: [
        'Tramites.model.RegistroModel',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Registro',
            model: 'Tramites.model.RegistroModel',
            proxy: {
                type: 'ajax',
                api: {
                    create: '../servidor/tramites/registro/save',
                    read: '../servidor/tramites/registro/get_tramite',
                    update: '../servidor/tramites/registro/update',
                    destroy: '../servidor/tramites/registro/update'
                },
                actionMethods: {
                    create: 'POST',
                    read: 'POST',
                    update: 'POST',
                    destroy: 'POST'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    encode: true,
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});