/*
 * File: app/view/panel/pnlNuevoViewController2.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.panel.pnlNuevoViewController2', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.panel.pnladministrar',

    onPanelActivate: function(component, eOpts) {
        Ext.getCmp('pnlAsuntosParams').removeAll();
        Ext.getCmp('pnlUnidadParametro').removeAll();
        Ext.getCmp('pnlJefeUnidad').removeAll();
        Ext.getCmp('pnlUsrAParametros1').removeAll();
        Ext.getCmp('pnlUsrAParametros').removeAll();
        var win = Ext.create('Tramites.view.administracion.AsuntosParametros');
        this.getView().down('#pnlAsuntosParams').add(win);
        win.show();
    },

    onPnlUnidadParametroActivate: function(component, eOpts) {
        Ext.getCmp('pnlAsuntosParams').removeAll();
        Ext.getCmp('pnlUnidadParametro').removeAll();
        Ext.getCmp('pnlJefeUnidad').removeAll();
        Ext.getCmp('pnlUsrAParametros1').removeAll();
        Ext.getCmp('pnlUsrAParametros').removeAll();
        var win = Ext.create('Tramites.view.administracion.UnidadParametro');
        this.getView().down('#pnlUnidadParametro').add(win);
        win.show();
    },

    onPnlJefeUnidadActivate: function(component, eOpts) {
        Ext.getCmp('pnlAsuntosParams').removeAll();
        Ext.getCmp('pnlUnidadParametro').removeAll();
        Ext.getCmp('pnlJefeUnidad').removeAll();
        Ext.getCmp('pnlUsrAParametros1').removeAll();
        Ext.getCmp('pnlUsrAParametros').removeAll();
        var win = Ext.create('Tramites.view.administracion.JefeUnidadDir');
        this.getView().down('#pnlJefeUnidad').add(win);
        win.show();
    },

    onPnlUsrAParametrosActivate: function(component, eOpts) {
        Ext.getCmp('pnlAsuntosParams').removeAll();
        Ext.getCmp('pnlUnidadParametro').removeAll();
        Ext.getCmp('pnlJefeUnidad').removeAll();
        Ext.getCmp('pnlUsrAParametros').removeAll();
        Ext.getCmp('pnlUsrAParametros1').removeAll();
        var win = Ext.create('Tramites.view.administracion.UsuarioParametroBasico');
        this.getView().down('#pnlUsrAParametros').add(win);
        win.show();
    },

    onPnlUsrAParametrosActivate1: function(component, eOpts) {
        Ext.getCmp('pnlAsuntosParams').removeAll();
        Ext.getCmp('pnlUnidadParametro').removeAll();
        Ext.getCmp('pnlJefeUnidad').removeAll();
        Ext.getCmp('pnlUsrAParametros').removeAll();
        Ext.getCmp('pnlUsrAParametros1').removeAll();
        var win = Ext.create('Tramites.view.administracion.RolesUsuario1');
        this.getView().down('#pnlUsrAParametros1').add(win);
        win.show();
    }

});
