/*
 * File: app/view/administracion/UnidadViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.administracion.UnidadViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.administracion.unidad',

    onBtnAgregarUnidadClick: function(button, e, eOpts) {
        //crea una nueva linea
        var grid = Ext.getCmp('grdUnidades2');
        var store = grid.getStore();
        store.insert(0,
        {
            UND_CODIGO: 0,
            UND_ACTIVO: 1
        });
    },

    onBtnLimpiarUnidades2Click: function(button, e, eOpts) {
        var strUnidad = Ext.getCmp('grdUnidades2').getStore();
        strUnidad.proxy.extraParams = {
            ac: 1//presenta todos las unidades activas
        };
        strUnidad.load();
    },

    onGrdUnidades2Render: function(component, eOpts) {
        this.onBtnLimpiarUnidades2Click();
    },

    onRowEditingEdit: function(editor, context, eOpts) {
        var me = this;
        if (context.record.modified)
        {
            var store = Ext.getCmp('grdUnidades2').getStore();
            var reco = context.record;
            store.add(reco);
            store.sync(
            {
                success: function(batch, success)
                {
                    store.commitChanges();
                    store.load();
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });

        }
    },

    onRowEditingCanceledit: function(editor, context, eOpts) {
        this.onBtnLimpiarUnidades2Click();
    }

});
