/*
 * File: app/view/consultar/winFiltroViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.consultar.winFiltroViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.consultar.winfiltro',

    onCbParamConsultaExpand: function(field, eOpts) {
        var strParametroCons = Ext.getCmp('cbParamConsulta').getStore();
        strParametroCons.proxy.extraParams={
            param:2
        };
        strParametroCons.load();
    },

    onBtnBuscarConsClick: function(button, e, eOpts) {
        var strConsulta1 = Ext.getStore('Consulta1');
        Ext.getCmp('grdConsulta1').getStore().removeAll();
        var chbanular = Ext.getCmp('chbAnulados').getValue();
        if(chbanular === false)
        chbanular = null;

        strConsulta1.proxy.extraParams = {
            busqueda: 1,//Parametro para elegir el tipo de busqueda
            codtramite:Ext.getCmp('numCodTramite').getValue(),
            anulado: chbanular,
            beneficiario: Ext.getCmp('txtBenefCons').getValue(),
            //parametro: Ext.getCmp('cbParamConsulta').getValue(),//cb Parametro de filtros
            parametro: Ext.getCmp('cbParametroPrincipal').getValue(),//cb Parametro principal
            undgasto:  Ext.getCmp('cbUGastoCons').getValue(),
            proyecto:  Ext.getCmp('txtProyCons').getValue(),
            asunto:  Ext.getCmp('cbAsuntoCons').getValue(),
            descripcion:  Ext.getCmp('txtDescCons').getValue(),
            noficio:  Ext.getCmp('txtOficioCons').getValue(),
            desde: Ext.getCmp('desdec').getValue(),
            hasta: Ext.getCmp('hastac').getValue()
        };
        strConsulta1.load();
        Ext.getCmp('cFiltro').destroy();
    },

    onBtnConsultarTodosClick: function(button, e, eOpts) {
        var me = this;
        var strConsulta1 = Ext.getCmp('grdConsulta1').getStore();
        strConsulta1.removeAll();
        strConsulta1.proxy.extraParams = {
            parametro : Ext.getCmp('cbParametroPrincipal').getValue()
        };
        strConsulta1.load();
        //Limpiar Filtros
        Ext.getCmp('numCodTramite').setValue(null);
        Ext.getCmp('chbAnulados').setValue(null);
        Ext.getCmp('txtBenefCons').setValue(null);
        Ext.getCmp('cbParamConsulta').setValue(null);
        Ext.getCmp('cbUGastoCons').setValue(null);
        Ext.getCmp('txtProyCons').setValue(null);
        Ext.getCmp('cbAsuntoCons').setValue(null);
        Ext.getCmp('txtDescCons').setValue(null);
        Ext.getCmp('txtOficioCons').setValue(null);
        Ext.getCmp('desdec').setValue(null);
        Ext.getCmp('hastac').setValue(null);

        me.onBtnBuscarConsClick();
    }

});
