/*
 * File: app/view/consultar/winEstadoCons.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.consultar.winEstadoCons', {
    extend: 'Ext.window.Window',
    alias: 'widget.consultar.winestadocons',

    requires: [
        'Tramites.view.consultar.winEstadoConsViewModel',
        'Tramites.view.consultar.winEstadoConsViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Date',
        'Ext.view.Table'
    ],

    controller: 'consultar.winestadocons',
    viewModel: {
        type: 'consultar.winestadocons'
    },
    modal: true,
    height: 316,
    width: 900,
    layout: 'fit',
    constrainHeader: true,
    title: 'Estados',

    items: [
        {
            xtype: 'gridpanel',
            id: 'grdEstadosCons',
            forceFit: true,
            store: 'Estado',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'UND_NOMBRE',
                    text: 'Destino'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'TIP_NOMBRE',
                    text: 'Estado'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'EST_FECHARECIBIDO',
                    text: 'Fecha de Ingreso',
                    format: 'Y-m-d H:i:s'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'EST_FECHAFIN',
                    text: 'Fecha de finalizacion',
                    format: 'Y-m-d H:i:s'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EST_OBSERVACION',
                    text: 'Observacion'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'EST_ASIGNADO_A',
                    text: 'Asignado A'
                }
            ],
            listeners: {
                render: 'onGrdEstadosConsRender'
            }
        }
    ]

});