/*
 * File: app/view/adminGeneral/UnidadDireccionamiento.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.adminGeneral.UnidadDireccionamiento', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.admingeneral.unidaddireccionamiento',

    requires: [
        'Tramites.view.adminGeneral.UnidadDireccionamientoViewModel',
        'Tramites.view.adminGeneral.UnidadDireccionamientoViewController',
        'Ext.form.field.ComboBox',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Check',
        'Ext.form.field.Checkbox',
        'Ext.grid.plugin.RowEditing'
    ],

    controller: 'admingeneral.unidaddireccionamiento',
    viewModel: {
        type: 'admingeneral.unidaddireccionamiento'
    },
    cls: 'myCls',
    layout: 'fit',
    title: 'Asignar Unidades de Direccionamiento',
    titleAlign: 'center',

    dockedItems: [
        {
            xtype: 'panel',
            dock: 'top',
            id: 'pnlCbDirec',
            margin: '10 0 0 0',
            layout: 'center',
            items: [
                {
                    xtype: 'combobox',
                    id: 'cbParametroUnidadDir',
                    margin: '0 0 10 0',
                    fieldLabel: 'Seleccione un Parámetro',
                    labelWidth: 150,
                    editable: false,
                    displayField: 'PRM_NOMBRE',
                    store: 'Parametro',
                    valueField: 'PRM_ID',
                    listeners: {
                        expand: 'onCbParametroUnidadDirExpand',
                        select: 'onCbParametroUnidadDirSelect'
                    }
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'panel',
            cls: 'myCls2',
            hidden: true,
            id: 'pnlUnidadesDir',
            scrollable: true,
            layout: 'fit',
            titleAlign: 'center',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'grdUnidadesDir',
                    title: 'Unidades de Direccionamiento',
                    titleAlign: 'center',
                    forceFit: true,
                    store: 'UnidadDir',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'UND_NOMBRE',
                            text: 'Unidad',
                            editor: {
                                xtype: 'textfield',
                                disabled: true
                            }
                        },
                        {
                            xtype: 'checkcolumn',
                            disabled: true,
                            dataIndex: 'UND_DIRECCIONAMIENTO',
                            text: 'Direccionamiento',
                            editor: {
                                xtype: 'checkboxfield'
                            }
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'rowediting',
                            listeners: {
                                edit: 'onRowEditingEdit',
                                canceledit: 'onRowEditingCanceledit'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});