/*
 * File: app/view/administracion/Unidad.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.administracion.Unidad', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.administracion.unidad',

    requires: [
        'Tramites.view.administracion.UnidadViewModel',
        'Tramites.view.administracion.UnidadViewController',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Check',
        'Ext.form.field.Checkbox',
        'Ext.view.Table',
        'Ext.grid.plugin.RowEditing'
    ],

    controller: 'administracion.unidad',
    viewModel: {
        type: 'administracion.unidad'
    },
    flex: 1,
    layout: 'fit',
    title: 'Unidades',

    items: [
        {
            xtype: 'panel',
            flex: 1,
            layout: 'fit',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'cbUnidades2',
                            enableKeyEvents: true,
                            hideTrigger: true,
                            displayField: 'UND_NOMBRE',
                            queryMode: 'local',
                            store: 'Unidad',
                            typeAhead: true,
                            valueField: 'UND_NOMBRE'
                        },
                        {
                            xtype: 'button',
                            id: 'btnAgregarUnidad',
                            iconCls: 'x-fa fa-plus',
                            text: 'Agregar',
                            listeners: {
                                click: 'onBtnAgregarUnidadClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnLimpiarUnidades2',
                            iconCls: 'x-fa fa-refresh',
                            text: 'Limpiar',
                            listeners: {
                                click: 'onBtnLimpiarUnidades2Click'
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'grdUnidades2',
                    forceFit: true,
                    store: 'Unidad',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'UND_NOMBRE',
                            text: 'Unidad',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'checkcolumn',
                            disabled: true,
                            dataIndex: 'UND_ACTIVO',
                            text: 'Activo',
                            editor: {
                                xtype: 'checkboxfield'
                            }
                        }
                    ],
                    viewConfig: {
                        height: 336
                    },
                    listeners: {
                        render: 'onGrdUnidades2Render'
                    },
                    plugins: [
                        {
                            ptype: 'rowediting',
                            listeners: {
                                edit: 'onRowEditingEdit',
                                canceledit: 'onRowEditingCanceledit'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});