/*
 * File: app/view/direccionar/winTramiteDetalle.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.direccionar.winTramiteDetalle', {
    extend: 'Ext.window.Window',
    alias: 'widget.direccionar.wintramitedetalle',

    requires: [
        'Tramites.view.direccionar.winTramiteDetalleViewModel',
        'Tramites.view.direccionar.winTramiteDetalleViewController',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.Label',
        'Ext.form.field.Date'
    ],

    controller: 'direccionar.wintramitedetalle',
    viewModel: {
        type: 'direccionar.wintramitedetalle'
    },
    modal: true,
    draggable: false,
    flex: 1,
    height: 496,
    id: 'winTramiteDetalle',
    width: 570,
    layout: 'fit',
    constrainHeader: true,
    title: 'Trámite',

    items: [
        {
            xtype: 'form',
            height: 1148,
            id: 'frmTramiteDetalle',
            itemId: 'myform2',
            scrollable: true,
            width: 551,
            layout: 'column',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'displayfield',
                    id: 'txtTraCod',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Número de trámite',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_CODIGO'
                },
                {
                    xtype: 'displayfield',
                    margin: '5 0 8 3',
                    width: 260,
                    fieldLabel: 'Fecha trámite',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_FECHA',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    id: 'cbParamForm',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Parámetro',
                    labelStyle: 'font-weight:bold;',
                    name: 'PRM_NOMBRE',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 3',
                    width: 260,
                    fieldLabel: 'Asunto',
                    labelStyle: 'font-weight:bold;',
                    name: 'ASU_DESCRIPCION',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Unidad Solicitante',
                    labelStyle: 'font-weight:bold;',
                    name: 'UND_NOMBRE',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 3',
                    width: 260,
                    fieldLabel: 'Unidad de gasto',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_GASTO',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 0',
                    width: 302,
                    fieldLabel: 'Número de oficio',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_OFICIO',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Beneficiario',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_BENEFICIARIO1',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 3',
                    width: 260,
                    fieldLabel: 'Cédula',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_CEDULA1',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Beneficiario',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_BENEFICIARIO2',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 3',
                    width: 260,
                    fieldLabel: 'Cédula',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_CEDULA2',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    width: 503,
                    fieldLabel: 'Proyecto/ partida presupuestaria',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_PROYECTO',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Posicion',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_POSICION',
                    value: ''
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Reserva',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_COMPROMISO',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 3',
                    width: 260,
                    fieldLabel: 'Descripción',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_DESCRIPCION',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    width: 504,
                    fieldLabel: 'Persona autoriza',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_PERSONA_AUTORIZA',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Telefono/Ext',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_TELEFONO',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 3',
                    width: 260,
                    fieldLabel: 'Valor',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_VALOR',
                    readOnly: true
                },
                {
                    xtype: 'displayfield',
                    margin: '0 0 3 0',
                    width: 240,
                    fieldLabel: 'Detalle factura',
                    labelStyle: 'font-weight:bold;',
                    name: 'TRA_DETALLE_FACTURA',
                    readOnly: true
                },
                {
                    xtype: 'panel',
                    layout: 'column',
                    items: [
                        {
                            xtype: 'label',
                            height: 31,
                            width: 489,
                            text: 'VIÁTICOS: (Solo si aplica)'
                        },
                        {
                            xtype: 'datefield',
                            border: false,
                            margin: '0 0 3 3',
                            width: 240,
                            fieldLabel: 'Fecha de viaje',
                            labelStyle: 'font-weight:bold;',
                            name: 'TRA_FECHA_VIAJE_VIATICO',
                            readOnly: true
                        },
                        {
                            xtype: 'displayfield',
                            margin: '0 0 3 0',
                            width: 260,
                            fieldLabel: 'Destino',
                            labelStyle: 'font-weight:bold;',
                            name: 'TRA_DESTINO_VIATICO',
                            readOnly: true
                        },
                        {
                            xtype: 'displayfield',
                            margin: '0 0 3 3',
                            width: 495,
                            fieldLabel: 'Responsable',
                            labelStyle: 'font-weight:bold;',
                            name: 'TRA_RESPONSABLE_VIATICO',
                            readOnly: true
                        },
                        {
                            xtype: 'displayfield',
                            margin: '0 0 3 0',
                            width: 495,
                            fieldLabel: 'Personas adicionales',
                            labelStyle: 'font-weight:bold;',
                            name: 'TRA_PERSONAS_ADIC_VIATICO',
                            readOnly: true
                        },
                        {
                            xtype: 'displayfield',
                            width: 495,
                            fieldLabel: 'Observación viaje',
                            labelStyle: 'font-weight:bold;',
                            name: 'TRA_OBSERV_VIAJE_VIATICO',
                            readOnly: true
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWinTramiteDetalleAfterRender'
    }

});