/*
 * File: app/view/adminGeneral/Asuntos.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.adminGeneral.Asuntos', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.admingeneral.asuntos',

    requires: [
        'Tramites.view.adminGeneral.AsuntosViewModel',
        'Tramites.view.adminGeneral.AsuntosViewController',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Check',
        'Ext.form.field.Checkbox',
        'Ext.view.Table',
        'Ext.grid.plugin.RowEditing'
    ],

    controller: 'admingeneral.asuntos',
    viewModel: {
        type: 'admingeneral.asuntos'
    },
    cls: 'myCls',
    layout: 'fit',
    title: 'Asuntos',
    titleAlign: 'center',

    items: [
        {
            xtype: 'panel',
            layout: 'fit',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'cbAsuntos',
                            emptyText: 'Buscar',
                            enableKeyEvents: true,
                            hideTrigger: true,
                            displayField: 'ASU_DESCRIPCION',
                            queryMode: 'local',
                            store: 'Asunto',
                            valueField: 'ASU_DESCRIPCION',
                            listeners: {
                                keyup: 'onCbAsuntosKeyup'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnAgregarAsunto',
                            iconCls: 'x-fa fa-plus',
                            text: 'Agregar',
                            listeners: {
                                click: 'onBtnAgregarAsuntoClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnLimpiarAsuntos2',
                            iconCls: 'x-fa fa-refresh',
                            text: 'Limpiar',
                            listeners: {
                                click: 'onBtnLimpiarAsuntos2Click'
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'grdAsuntos2',
                    forceFit: true,
                    store: 'Asunto',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            align: 'center',
                            dataIndex: 'ASU_DESCRIPCION',
                            text: 'Asunto',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'checkcolumn',
                            disabled: true,
                            dataIndex: 'ASU_ACTIVO',
                            text: 'Activo',
                            editor: {
                                xtype: 'checkboxfield'
                            }
                        }
                    ],
                    plugins: [
                        {
                            ptype: 'rowediting',
                            listeners: {
                                edit: 'onRowEditingEdit',
                                canceledit: 'onRowEditingCanceledit'
                            }
                        }
                    ],
                    listeners: {
                        render: 'onGrdAsuntos2Render'
                    }
                }
            ]
        }
    ]

});