/*
 * File: app/view/adminGeneral/RolesUsuarioViewController2.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.adminGeneral.RolesUsuarioViewController2', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.administracion.rolesusuario1',

    onCbUsuarioBuscarKeyup: function(textfield, e, eOpts) {
        //presenta usuarios similares al que se esta escribiendo
        var txtUsuario = Ext.getCmp('cbUsuarioBuscar1').getValue();
        if(txtUsuario !== null && e.isSpecialKey() === false){//8 = Backspace
            var strUsuario = Ext.getCmp('cbUsuarioBuscar1').getStore();
            strUsuario.removeAll();
            Ext.Ajax.request({
                method: 'post',
                url: '../servidor/tramites/usuario/getUsuarioBusqueda',
                params: {
                    usuario: txtUsuario
                },
                success: function (response, options) {
                    strUsuario.load();
                    Ext.getCmp('cbUsuarioBuscar1').expand();
                }
            });
        }
    },

    onCbUsuarioBuscarSelect: function(combo, record, eOpts) {
        var txtUsuario = Ext.getCmp('cbUsuarioBuscar1').getValue();
        var strUsuario = Ext.getCmp('cbUsuarioBuscar1').getStore();
        strUsuario.removeAll();
        Ext.Ajax.request({
            method: 'post',
            url: '../servidor/tramites/usuario/getUsuarioBusqueda',
            params: {
                usuario: txtUsuario
            },
            success: function (response, options) {
                strUsuario.load();
            }
        });
    },

    onBtnLimpiarUsuarioClick: function(button, e, eOpts) {
        Ext.getCmp('grdUsuarioRol1').getStore().removeAll();
        var strUsuario = Ext.getStore('Usuario');
        strUsuario.proxy.extraParams={
            usr: 0//trae todos los usuarios
        };
        strUsuario.load();

        Ext.getCmp('grdRol1').getStore().removeAll();
        Ext.getCmp('btnAgregarRol1').setHidden(true);
        Ext.getCmp('btnQuitarRol1').setHidden(true);
    },

    onGrdUsuarioRolRender: function(component, eOpts) {
        this.onBtnLimpiarUsuarioClick();
    },

    onGrdUsuarioRolItemClick: function(dataview, record, item, index, e, eOpts) {
        Ext.getCmp('grdRol1').getStore().removeAll();
        Ext.getCmp('btnAgregarRol1').setHidden(false);
        Ext.getCmp('btnQuitarRol1').setHidden(false);
        var g = Ext.getCmp('grdUsuarioRol1');
        var rec = g.selection;
        var strRoles = Ext.getCmp('grdRol1').getStore();
        strRoles.removeAll();
        strRoles.proxy.extraParams = {
            usuario: rec.data.USR_USUARIO,
            parametro: Ext.getCmp('cbParametroPrincipal').getValue()
        };
        strRoles.load();
        Ext.getCmp('btnAgregarRol1').setHidden(false);
        Ext.getCmp('btnQuitarRol1').setHidden(false);
    },

    onBtnAgregarRolClick: function(button, e, eOpts) {
        var grid = Ext.getCmp('grdRol1');
        var store = grid.getStore();
        var g = Ext.getCmp('grdUsuarioRol1');
        var arrayKeys = g.getSelectionModel().selected.items;
        var indice = g.getSelectionModel().selectionStartIdx;
        if(arrayKeys.length === 0){
            Ext.Msg.alert('Error', 'Debe escoger un usuario');
        }
        else
        {
            //crea una ueva linea en la grid
            var rec = g.selection;
            var usuariot = rec.data.USR_USUARIO;
            var strRol = Ext.getCmp('cbRoles1').getStore();
            strRol.proxy.extraParams = {
                usuario: usuariot,
                parametro : Ext.getCmp('cbParametroPrincipal').getValue()
            };
            store.insert(0,
            {
                USR_USUARIO: usuariot,
                ROL_ID: 0
            });
            strRol.load();
        }
    },

    onBtnQuitarRolClick: function(button, e, eOpts) {
        var g = Ext.getCmp('grdUsuarioRol1');
        var arrayKeys = g.getSelectionModel().selected.items;
        var indice = g.getSelectionModel().selectionStartIdx;
        if(arrayKeys.length === 0)
        Ext.Msg.alert('Error', 'Debe escoger un usuario');
        else
        {
            var grid = Ext.getCmp('grdRol1');
            var arrayKeys = grid.getSelectionModel().selected.items;
            var indice = grid.getSelectionModel().selectionStartIdx;
            if(arrayKeys.length === 0)
            Ext.Msg.alert('Error', 'Debe escoger un rol');
            else
            {
                var store = grid.getStore();
                var rec = grid.selection;
                var reco = g.selection;
                store.remove(rec);
                store.sync(
                {
                    params:{
                        usuario: reco.data.USR_USUARIO,
                        rol: rec.data.ROL_ID,
                        parametro : Ext.getCmp('cbParametroPrincipal').getValue()
                    },
                    success: function(batch, success)
                    {
                        store.commitChanges();
                        store.load();
                    },

                    failure: function(batch, success)
                    {
                        Ext.Msg.alert('Error', 'Hubor un error');
                    }
                });
            }
        }
    },

    onRowEditingEdit: function(editor, context, eOpts) {
        var me = this;
        if (context.record.modified)
        {
            var store = Ext.getCmp('grdRol1').getStore();
            var reco = context.record;
            store.add(reco);
            store.sync(
            {
                params:{
                    usuario: reco.data.USR_USUARIO,
                    parametro: Ext.getCmp('cbParametroPrincipal').getValue(),
                },
                success: function(batch, success)
                {
                    store.commitChanges();
                    store.load();
                },

                failure: function(batch, success)
                {
                    Ext.Msg.alert('Error', 'Hubor un error');
                }
            });

        }
        //me.onGrdUsuarioRolItemClick();
    },

    onGrdRolCellDblClick: function(tableview, td, cellIndex, record, tr, rowIndex, e, eOpts) {
        if(record.data.ROL_ID === 0)//habilita el bombobox solo en la linea en blanco
        Ext.getCmp('cbRoles1').setDisabled(false);
        else
        Ext.getCmp('cbRoles1').setDisabled(true);
    }

});
