/*
 * File: app/view/adminGeneral/UnidadGasto.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.view.adminGeneral.UnidadGasto', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.admingeneral.unidadgasto',

    requires: [
        'Tramites.view.adminGeneral.UnidadViewModel1',
        'Tramites.view.adminGeneral.UnidadViewController1',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Check',
        'Ext.form.field.Checkbox',
        'Ext.grid.plugin.RowEditing'
    ],

    controller: 'admingeneral.unidadgasto',
    viewModel: {
        type: 'admingeneral.unidadgasto'
    },
    cls: 'myCls',
    flex: 1,
    layout: 'fit',
    title: 'Unidades de Gasto',
    titleAlign: 'center',

    items: [
        {
            xtype: 'panel',
            flex: 1,
            layout: 'fit',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'combobox',
                            id: 'cbUndGastoBus',
                            width: 228,
                            emptyText: 'Ingrese una Unidad de Gasto',
                            enableKeyEvents: true,
                            hideTrigger: true,
                            displayField: 'GST_NOMBRE',
                            store: 'UnidadGasto',
                            valueField: 'GST_NOMBRE',
                            listeners: {
                                keyup: 'onCbUndGastoBusquedaKeyup'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnAgregarUnidadGasto',
                            iconCls: 'x-fa fa-plus',
                            text: 'Agregar',
                            listeners: {
                                click: 'onBtnAgregarUnidadGastoClick'
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnLimpiarUnidadGasto',
                            iconCls: 'x-fa fa-refresh',
                            text: 'Limpiar',
                            listeners: {
                                click: 'onBtnLimpiarUnidadGastoClick'
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'grdUnidadesGasto',
                    forceFit: true,
                    store: 'UnidadGasto',
                    viewConfig: {
                        height: 336
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GST_NOMBRE',
                            text: 'Unidad de Gasto',
                            editor: {
                                xtype: 'textfield',
                                allowBlank: false
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'GST_DESCRIPCION',
                            text: 'Descripción',
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'checkcolumn',
                            disabled: true,
                            dataIndex: 'GST_ACTIVO',
                            text: 'Activo',
                            editor: {
                                xtype: 'checkboxfield'
                            }
                        }
                    ],
                    listeners: {
                        render: 'onGrdUnidades2Render'
                    },
                    plugins: [
                        {
                            ptype: 'rowediting',
                            listeners: {
                                edit: 'onRowEditingEdit',
                                canceledit: 'onRowEditingCanceledit'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});