/*
 * File: app/model/UnidadParametroModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Tramites.model.UnidadParametroModel', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    idProperty: 'PRM_ID',

    fields: [
        {
            type: 'int',
            name: 'UND_CODIGO'
        },
        {
            type: 'int',
            name: 'PRM_ID'
        },
        {
            type: 'string',
            name: 'PRM_NOMBRE'
        },
        {
            type: 'string',
            name: 'UND_NOMBRE'
        },
        {
            type: 'int',
            name: 'UND_PRM_ID'
        },
        {
            type: 'string',
            name: 'UND_PRM'
        }
    ]
});